import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  const isSignedIn = useSession().data?.user !== undefined;
  console.log(isSignedIn);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen  flex-col bg-[#111111] px-8">
        <div className="mx-auto mb-16 mt-12 flex max-w-2xl flex-col items-start justify-center">
          <h1 className="mb-4 text-3xl font-bold tracking-tight text-black dark:text-white md:text-5xl">
            Guestbook
          </h1>
          <p className="mb-4 text-gray-600 dark:text-gray-400">
            Leave a comment below. It could be anything – appreciation,
            information, wisdom, or even humor. Surprise me!
          </p>
          <div className="w-full bg-[#101629] p-4">
            <h2 className="text-xl dark:text-white">Sign the Guestbook</h2>
            <p className="my-2 text-white">
              Share a message for a future visitor of my site.
            </p>
            {isSignedIn ? (
              <>
                <div className="flex justify-around rounded-md bg-[#222222] px-2 py-4">
                  <input
                    type="text"
                    placeholder="Your message..."
                    className="bg-[#222222] text-white focus:outline-none"
                  />
                  <button className="h-8 rounded-sm bg-[#333333] px-4 text-white focus:outline-none">
                    Sign
                  </button>
                </div>
                <p className="text-green-400">
                  Hooray! Thanks for signing my Guestbook.
                </p>
              </>
            ) : (
              <div className="flex rounded-md px-2 py-4">
                <button className="h-8 rounded-sm bg-[#333333] px-4 text-white focus:outline-none">
                  Login
                </button>
              </div>
            )}
          </div>
          <div className="my-6">
            <div className="text-white">
              <h3>hi</h3>
              <div className="flex gap-4">
                <p>daniel</p>
                <p>31 Dec 2022 at 10:27 PM</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
